// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// c_basis1
Rcpp::List c_basis1(Eigen::MappedSparseMatrix<double> A);
RcppExport SEXP _CB_c_basis1(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MappedSparseMatrix<double> >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(c_basis1(A));
    return rcpp_result_gen;
END_RCPP
}
// c_basis2
Rcpp::List c_basis2(Eigen::MappedSparseMatrix<double> A, double eps_limit);
RcppExport SEXP _CB_c_basis2(SEXP ASEXP, SEXP eps_limitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MappedSparseMatrix<double> >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type eps_limit(eps_limitSEXP);
    rcpp_result_gen = Rcpp::wrap(c_basis2(A, eps_limit));
    return rcpp_result_gen;
END_RCPP
}
// likelihood
Eigen::SparseMatrix<double> likelihood(Eigen::SparseMatrix<double> Q);
RcppExport SEXP _CB_likelihood(SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::SparseMatrix<double> >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(likelihood(Q));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CB_c_basis1", (DL_FUNC) &_CB_c_basis1, 1},
    {"_CB_c_basis2", (DL_FUNC) &_CB_c_basis2, 2},
    {"_CB_likelihood", (DL_FUNC) &_CB_likelihood, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_CB(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
