# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#' sorts integervector
NULL

#'
#' setdiff(A,B) stored in C
#'
NULL

#'
#' Creating a basis from the matrix A
#' @param A [nxk matrix] must have rank k
#'
c_basis1_cpp <- function(A) {
    .Call(`_CB_c_basis1_cpp`, A)
}

#'
#' Creating a basis from the matrix A
#' @param A [nxk matrix] must have rank k
#' @param eps_limit [double] used as a limit of small value
c_basis2_cpp <- function(A, eps_limit = 10e-6) {
    .Call(`_CB_c_basis2_cpp`, A, eps_limit)
}

likelihood <- function(Q) {
    .Call(`_CB_likelihood`, Q)
}

